### ISSUE TITLE
How to use dojot under corporative proxy?

### ISSUE THREAD

**Issue by wellersonlopes** [dojot/docker-compose#81]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Plataform don't start.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Install dojot/docker-compose in the host behind proxy
2. Start with "docker-compose up -d"
3. Three containers are rebooting. [dojot_kong-config, dojot_persister, dojot_auth]
3. Plataform don't start. 

* **What is the expected behavior?**
Plataform starts behind proxy.
Suggestion: Setup in docker-compose.yml the containers that need of internet access.

* **What is the motivation / use case for changing the behavior?**
Allow the use of the dojot/docker-compose under corporative proxy.

* **Please tell us about your environment:**
  
  - Version: 0.3.1
  - Docker version: 1.13.1, build 8633870/1.13.1
  - Operating system: CentOS Linux release 7.5.1804 (Core)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by giovannicuriel** [comment]
Hi!
We created a small Dockerfile to generate a "static" version of Kong (this image has all dependencies preinstalled for its plugins, namely `mutualauthentication` and `pep-kong`). We ran a few tests blocking all outgoing traffic from the containers and it seems to be working. Could you try in your scenario?

You could just change the image from `apigw` service:

```yaml
apigw:
    image: dojot/kong:v0.2.1
    restart: always
    depends_on:
      postgres:
....
```

to
```yaml
apigw:
    image: dojot/kong:v0.2.1-static
    restart: always
    depends_on:
      postgres:
....
```
